### ISSUE TITLE
Count does not work with preview emulator

### ISSUE THREAD

**Issue by jvalkeejarvi** [Azure/azure-cosmos-db-emulator-docker#118]
Following query does not work with cosmosEmulatorVnextPreview:
```sql
SELECT count(0) FROM c
```

**Comment by lionelc** [comment]
count(*) should work. Not all the dialects are supported as of now.

**Comment by DmitriMelnikov** [comment]
The fix will be shipped in the post Nov27 release. 

*And we still would not support count(*) as CosmosDB REST API does not support it.

**Comment by kmandalas** [comment]
This has also as side-effect Spring Data queries like this to fail:

`boolean existsByPrincipalAndType(String principal, String auditType);`

with error:

```
com.azure.spring.data.cosmos.exception.CosmosAccessException: Failed to get count value
"innerErrorMessage":"Aggref found in non-Agg plan node,..."
```

Integration test here: https://github.com/kmandalas/cosmosdb-vnext/blob/2791f59618583e719d2645064899b251ef738cc4/src/test/java/com/example/demo/audits/DemoAuditRepositoryIntegrationTest.java#L62

**Comment by DmitriMelnikov** [comment]
@kmandalas can you please take latest version of the emulator and try again? This time exception should include more information for us to understand the issue

**Comment by DmitriMelnikov** [comment]
Our publish pipeline did not work until recently preventing the fixes from shipment. Pipeline is fixed now, and the fixes should be available. Please use ```docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview``` to donwload the latest image and ```docker inspect mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview``` to validate the latest build: Created field should be no less than 2024-12-16T20:25:13.18725592Z

**Comment by xgerman** [comment]
fixed in latest release - please reopen if it's still an issue.

**Comment by kmandalas** [comment]
@xgerman I downloaded the latest image but my tests now fail cause connectivity is broken:

```
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (https://localhost:62435/ should return HTTP [200])
.
.
.
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
```

Until now, it was working fine initializing the container with Java/Spring/TestContainers like this:

```
@Container
    static CosmosDBEmulatorContainer cosmosDbContainer = new CosmosDBEmulatorContainer(
            DockerImageName.parse("mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview"))
            .withCommand("--protocol", "https")
            .waitingFor(Wait.forHttps("/").forStatusCode(200).allowInsecure())
            .withStartupTimeout(Duration.ofMinutes(1));
```

After the last update, the above mentioned problem occurs.

**Comment by kmandalas** [comment]
@xgerman @DmitriMelnikov I was able to test after pulling latest image again. The operation still fails. Stacktrace is:

```
2025-02-03T10:54:29.306+02:00 DEBUG 18512 --- [           main] c.a.c.implementation.SqlQuerySpecLogger  : SELECT VALUE COUNT(1) FROM r WHERE (r.principal = @principal0 AND r.type = @type1) 
2025-02-03T10:54:33.077+02:00 ERROR 18512 --- [ctor-http-nio-1] c.a.c.i.query.DocumentProducer           : Unexpected failure, Context: n/a

com.azure.cosmos.CosmosException: {"innerErrorMessage":"Exception while reading from stream Cosmos query text: SELECT VALUE COUNT(1) FROM r WHERE (r.principal = @principal0 AND r.type = @type1)  -> SELECT COUNT(1) FROM %s AS r WHERE (cosmos_catalog.cosmos_eq(r.document, $1 ) AND cosmos_catalog.cosmos_eq(r.document, $2 )), StatusCode: InternalServerError","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.54.0 MacOSX/14.6.1 JRE/21.0.2 az-sd-cos/5.9.1az-sp-cos/5.9.1","activityId":"b066fdcb-7fcd-4a54-84ff-1ef58b2ca73a","requestLatencyInMs":3766,"requestStartTimeUTC":"2025-02-03T08:54:29.309371Z","requestEndTimeUTC":"2025-02-03T08:54:33.076114Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["primary"],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatisticsList":[{"sessionToken":"0:-1#1","operationType":"Query","resourceType":"Document","statusCode":500,"subStatusCode":0,"requestCharge":0.0,"requestTimeline":[{"eventName":"connectionAcquired","startTimeUTC":"2025-02-03T08:54:29.309637Z","durationInMilliSecs":0.125},{"eventName":"connectionConfigured","startTimeUTC":"2025-02-03T08:54:29.309762Z","durationInMilliSecs":0.02},{"eventName":"requestSent","startTimeUTC":"2025-02-03T08:54:29.309782Z","durationInMilliSecs":0.33},{"eventName":"transitTime","startTimeUTC":"2025-02-03T08:54:29.310112Z","durationInMilliSecs":3765.03},{"eventName":"received","startTimeUTC":"2025-02-03T08:54:33.075142Z","durationInMilliSecs":0.364}],"partitionKeyRangeId":"0","responsePayloadSizeInBytes":0,"exceptionMessage":"Exception while reading from stream Cosmos query text: SELECT VALUE COUNT(1) FROM r WHERE (r.principal = @principal0 AND r.type = @type1)  -> SELECT COUNT(1) FROM %s AS r WHERE (cosmos_catalog.cosmos_eq(r.document, $1 ) AND cosmos_catalog.cosmos_eq(r.document, $2 )), StatusCode: InternalServerError","exceptionResponseHeaders":"{Transfer-Encoding=chunked, Server=PGSQL, x-ms-session-token=0:-1#1, x-ms-documentdb-partitionkeyrangeid=0, x-ms-interopandsdk-time-ms=3763, x-ms-gatewayversion=2.0.0-unknown, Date=Mon, 03 Feb 2025 08:54:32 GMT, x-ms-activity-id=b066fdcb-7fcd-4a54-84ff-1ef58b2ca73a, Content-Type=application/json}"}],"samplingRateSnapshot":1.0,"systemInformation":{"usedMemory":"125902 KB","availableMemory":"9311282 KB","systemCpuLoad":"(2025-02-03T08:54:33.065791Z 12.3%)","availableProcessors":11},"clientCfgs":{"id":1,"machineId":"uuid:6a42097a-eeea-4a0d-9a7a-81704a0fd266","connectionMode":"GATEWAY","numberOfClients":3,"excrgns":"[]","clientEndpoints":{"https://localhost:58710":3},"connCfg":{"rntbd":null,"gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: false, cs: false, rv: true)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])","proactiveInitCfg":"","e2ePolicyCfg":"","sessionRetryCfg":""}}}
	at com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:478) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at com.azure.cosmos.implementation.RxGatewayStoreModel.validateOrThrow(RxGatewayStoreModel.java:504) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$1(RxGatewayStoreModel.java:365) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:500) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:782) ~[reactor-netty-http-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1349) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1389) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]


com.azure.spring.data.cosmos.exception.CosmosAccessException: Failed to get count value
```

**Comment by kmandalas** [comment]
@xgerman should I open other issue for this?

**Comment by Blackbaud-JasonBodnar** [comment]
We have the same issue:

```
{
  "innerErrorMessage": "[\"One of the specified pre-condition is not met. Learn more: https://aka.ms/CosmosDB/sql/errors/precondition-failed\"]",
  "cosmosDiagnostics": {
    "userAgent": "azsdk-java-cosmos/4.67.0 Linux/6.8.0-55-generic JRE/19.0.2 az-sd-cos/5.20.0",
    "activityId": "b98c7107-1596-4ab6-b080-9503bfdb305f",
    "requestLatencyInMs": 159,
    "requestStartTimeUTC": "2025-03-21T18:08:00.969780246Z",
    "requestEndTimeUTC": "2025-03-21T18:08:01.129211838Z",
    "responseStatisticsList": [
      {
        "storeResult": {
          "storePhysicalAddress": "rntbd://cdb-ms-prod-eastus1-be134.documents.azure.com:14097/apps/594d5a7c-624c-474c-a439-a0a5c13fc59e/services/24c9ef4a-8694-4ebe-873f-4fcc1452974e/partitions/9c41c9e6-0c07-4222-910d-7ecfa9f48f2f/replicas/133870512008503063p/",
          "lsn": 2,
          "quorumAckedLSN": 2,
          "currentReplicaSetSize": 3,
          "globalCommittedLsn": 2,
          "partitionKeyRangeId": "0",
          "isValid": true,
          "statusCode": 412,
          "subStatusCode": 1110,
          "isGone": false,
          "isNotFound": false,
          "isInvalidPartition": false,
          "isThroughputControlRequestRateTooLarge": false,
          "requestCharge": 1,
          "itemLSN": -1,
          "sessionToken": "0:-1#2",
          "backendLatencyInMs": 0.748,
          "retryAfterInMs": null,
          "exceptionMessage": "[\"One of the specified pre-condition is not met. Learn more: https://aka.ms/CosmosDB/sql/errors/precondition-failed\"]",
          "exceptionResponseHeaders": "{x-ms-current-replica-set-size=4, x-ms-last-state-change-utc=Fri, 21 Mar 2025 17:20:12.543 GMT, x-ms-request-duration-ms=0.748, x-ms-session-token=0:-1#2, lsn=2, x-ms-request-charge=1.00, x-ms-schemaversion=1.19, x-ms-transport-request-id=17, x-ms-number-of-read-regions=0, x-ms-current-write-quorum=3, x-ms-cosmos-quorum-acked-llsn=2, x-ms-quorum-acked-lsn=2, x-ms-activity-id=b98c7107-1596-4ab6-b080-9503bfdb305f, x-ms-xp-role=1, x-ms-global-Committed-lsn=2, x-ms-cosmos-llsn=2, x-ms-documentdb-partitionkeyrangeid=0, x-ms-serviceversion= version=2.14.0.0, x-ms-substatus=1110}",
          "replicaStatusList": {
            "Ignoring": [
              "14385:S:Connected",
              "14022:S:Connected",
              "14099:S:Connected"
            ],
            "Attempting": [
              "14097:P:Connected"
            ]
          },
          "transportRequestTimeline": [
            {
              "eventName": "created",
              "startTimeUTC": "2025-03-21T18:08:00.972538531Z",
              "durationInMilliSecs": 0.033148
            },
            {
              "eventName": "queued",
              "startTimeUTC": "2025-03-21T18:08:00.972571679Z",
              "durationInMilliSecs": 0.00064
            },
            {
              "eventName": "channelAcquisitionStarted",
              "startTimeUTC": "2025-03-21T18:08:00.972572319Z",
              "durationInMilliSecs": 0.261654
            },
            {
              "eventName": "pipelined",
              "startTimeUTC": "2025-03-21T18:08:00.972833973Z",
              "durationInMilliSecs": 34.959483
            },
            {
              "eventName": "transitTime",
              "startTimeUTC": "2025-03-21T18:08:01.007793456Z",
              "durationInMilliSecs": 120.279883
            },
            {
              "eventName": "decodeTime",
              "startTimeUTC": "2025-03-21T18:08:01.128073339Z",
              "durationInMilliSecs": 0.096292
            },
            {
              "eventName": "received",
              "startTimeUTC": "2025-03-21T18:08:01.128169631Z",
              "durationInMilliSecs": 0.882988
            },
            {
              "eventName": "completed",
              "startTimeUTC": "2025-03-21T18:08:01.129052619Z",
              "durationInMilliSecs": 0.01101
            }
          ],
          "rntbdRequestLengthInBytes": 614,
          "rntbdResponseLengthInBytes": 345,
          "requestPayloadLengthInBytes": 107,
          "responsePayloadLengthInBytes": 345,
          "channelStatistics": {
            "channelId": "3932ac8a",
            "channelTaskQueueSize": 0,
            "pendingRequestsCount": 0,
            "lastReadTime": "2025-03-21T18:08:00.963415118Z",
            "waitForConnectionInit": false
          },
          "serviceEndpointStatistics": {
            "availableChannels": 1,
            "acquiredChannels": 0,
            "executorTaskQueueSize": 0,
            "inflightRequests": 1,
            "lastSuccessfulRequestTime": "2025-03-21T18:08:00.965Z",
            "lastRequestTime": "2025-03-21T18:08:00.504Z",
            "createdTime": "2025-03-21T18:08:00.505049793Z",
            "isClosed": false,
            "cerMetrics": {}
          }
        },
        "requestResponseTimeUTC": "2025-03-21T18:08:01.129211838Z",
        "requestStartTimeUTC": "2025-03-21T18:08:00.972538531Z",
        "requestResourceType": "Document",
        "requestOperationType": "Patch",
        "requestSessionToken": null,
        "e2ePolicyCfg": null,
        "excludedRegions": null,
        "sessionTokenEvaluationResults": [],
        "locationToLocationSpecificHealthContext": {
          "v": null
        }
      }
    ],
    "supplementalResponseStatisticsList": [],
    "addressResolutionStatistics": {},
    "regionsContacted": [
      "east us"
    ],
    "retryContext": {
      "statusAndSubStatusCodes": null,
      "retryLatency": 0,
      "retryCount": 0
    },
    "metadataDiagnosticsContext": {
      "metadataDiagnosticList": null
    },
    "serializationDiagnosticsContext": {
      "serializationDiagnosticsList": [
        {
          "serializationType": "ITEM_SERIALIZATION",
          "startTimeUTC": "2025-03-21T18:08:00.970181822Z",
          "endTimeUTC": "2025-03-21T18:08:00.970946167Z",
          "durationInMilliSecs": 0.764345
        }
      ]
    },
    "gatewayStatisticsList": [],
    "samplingRateSnapshot": 1,
    "bloomFilterInsertionCountSnapshot": 0,
    "systemInformation": {
      "usedMemory": "248188 KB",
      "availableMemory": "276100 KB",
      "systemCpuLoad": "(2025-03-21T18:07:53.440516312Z 14.5%), (2025-03-21T18:07:58.440541547Z 14.5%)",
      "availableProcessors": 16
    },
    "clientCfgs": {
      "id": 1,
      "machineId": "uuid:ad8b9cbc-800f-447f-b150-1b1f5ee12703",
      "connectionMode": "DIRECT",
      "numberOfClients": 2,
      "excrgns": "[]",
      "clientEndpoints": {
        "https://jason-bodnar-cosmos-sql.documents.azure.com:443/": 2
      },
      "connCfg": {
        "rntbd": "(cto:PT5S, nrto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:true)",
        "gw": "(cps:1000, nrto:PT1M, icto:PT1M, cto:PT45S, p:false)",
        "other": "(ed: true, cs: false, rv: true)"
      },
      "consistencyCfg": "(consistency: null, mm: true, prgns: [])",
      "proactiveInitCfg": "",
      "e2ePolicyCfg": "",
      "sessionRetryCfg": "",
      "partitionLevelCircuitBreakerCfg": "(cb: false, type: CONSECUTIVE_EXCEPTION_COUNT_BASED, rexcntt: 10, wexcntt: 5)"
    }
  }
}
```
